name: QuestPMMP
main: AlexBrin\Quest\quests
version: 1.1
api: 7.0.0
author: Gamchik
fixer: GamerSoiCon / SaltyPixelDevz
translator: SaltyPixelDevz

commands:
  quest:
    description: "§eQuests"
    default: true
